server:
  port: 8771
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    service-feign:
      path: /service-feign/**
