server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/gongjian1990/springcloud-demo
          search-paths: respo
          username:
          password:

