server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri:
          search-paths:
          username:
          password:

